### ISSUE TITLE
Double clicking on card

### ISSUE THREAD

**Issue by kjh311** [kjh311/Game_of_Thrones_Concentration_Game#1]
I have a small bug with my memory game.  When I click on a card it gets pushed to an empty array,  memory_value = []. After 2 cards get added the array gets wiped clean.  The problem is if I click on the same card twice the array is filled with the same card and the player's turn switches.  Inside my click event listener for the #a card I tried adding: 
if  (memory_value[0] === $('#a')){
    return; //do nothing
}
but it doesn't work.  Probably a simple syntax error. Thnx!

**Comment by stanleycyang** [comment]
Used indexOf to check if the value exists in the array

**Comment by ghost** [comment]
@kjh311 Remember to use Markdown in your issues!

If you put backticks around your code, it will look like code and be easier to read. Use one backtick on either side to delimit inline code like this:

The text ``memory_value = []`` becomes `memory_value = []`.

Use three backticks and the language name (code fences) for multiple lines, like this:

<pre>
```javascript
if (memory_value[0] === $('#a')){
return; //do nothing
}
```
</pre>

becomes...

``` javascript
if (memory_value[0] === $('#a')){
return; //do nothing
}
```

**Comment by ghost** [comment]
Also: indent! :smile:
